### ISSUE TITLE
Описать требования к API

### ISSUE THREAD

**Issue by libhet** [beerMapSPB/mobile_app#4]
Готов заняться разработкой API на фласке. Для этого нужны расписанные требования.

**Comment by SlowBroshka** [comment]
Предлагаю пока чуть подождать с API.

1. Давай для начала заведем репу с фласком
2. Убедимся, что она у меня и у тебя собирается
3. Сделай там какую нить одну echo команду
4. Научимся разворачивать его на сервере
5. Убедимся что свзяка работает (`admin_panel` <-> `server` и `mobile_app` <-> `server`)
6. И только после этого начнем наращивать функционал API

**Comment by TatianaFomina** [comment]
> Убедимся что свзяка работает (admin_panel <-> server и mobile_app <-> server)
а это что значит?

**Comment by SlowBroshka** [comment]
> > Убедимся что свзяка работает (admin_panel <-> server и mobile_app <-> server)
> > а это что значит?

Ответы на простые запросы приходят. Нужные порты на тачке открыты.
